### ISSUE TITLE
Symfony 4 : how to deal with asset versionning?

### ISSUE THREAD

**Issue by jeremy-richard** [Limenius/ReactBundle#30]
Hi, I'm struggling with [asset versionning](http://symfony.com/doc/current/frontend/encore/versioning.html) et SSR.

I would like to have both the `cache key` and `server_bundle_path` to be set accordingly to the content of the `json_manifest_path`.

Here is the `config/packages/framework.yaml`
```yaml
framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        storage_id: session.storage.php_bridge
        handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    assets:
        json_manifest_path: '%kernel.project_dir%/web/dist/manifest.json'
    cache:
        # The app cache caches to the filesystem by default. Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
```

And here is the `config/packages/limenius_react.yaml`
```yaml
limenius_react:
    # Other options are "server_side" and "client_side"
    #default_rendering: "both"
    default_rendering: "both"
    serverside_rendering:
        cache:
            enabled: true
            # name of your app, it is the key of the cache where the snapshot will be stored.
            key: "main.78de05ae.js"
        # In case of error in server-side rendering, throw exception
        fail_loud: false
        # Replay every console.log message produced during server-side rendering
        # in the JavaScript console
        # Note that if enabled it will throw a (harmless) React warning
        trace: false
        # Mode can be `"phpexecjs"` (to execute Js from PHP using PhpExecJs),
        # or `"external_server"` (to rely on an external node.js server)
        # Default is `"phpexecjs"`
        mode: "phpexecjs"
        # Only used with mode `phpexecjs`
        #  Location of the server bundle, that contains React and React on Rails.
        #  null will default to `%kernel.root_dir%/Resources/webpack/server-bundle.js`
        server_bundle_path: "%kernel.project_dir%/web/build/js/main.78de05ae.js"
        # Only used with mode `external`
        #  Location of the unix socket to communicate with a dummy node.js server
        #  Such as the one in `Resources/node-server/server.js`
        #  null will default to `%kernel.root_dir%/Resources/node-server/node.sock
        server_socket_path: null
```

Everytime the hash changes I have to edit the configuration. Is there a way to use the Asset Component, and Version Strategy to set both `serverside_rendering.cache.key` and `serverside_rendering.server_bundle_path` ?

I tried to set a parameter inside the `src/Kernel.php`, so I would use the values `"%reactjs%" `and `"%kernel.project_dir%/web/build/js/%reactjs%"`
```php
protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader)
{
     $container->setParameter('reactjs', 'main.78de05ae.js');
...
```
But so far I didn't find a way to retrieve the Version Strategy instance.

**Comment by jeremy-richard** [comment]
I found a way to do it. I have to override both `phpexecjs_react_renderer` and `react_renderer` then use methods calls to set `@assets.packages` so I could use it to define the `server_bundle_path`.
Here is my services.yaml settings : 
```yml
    limenius_react.phpexecjs_react_renderer:
        class: App\ReactRenderer\Renderer\PhpExecJsReactRenderer
        arguments:
            - '%kernel.project_dir%/web'
            - '%limenius_react.fail_loud%'
            - '@limenius_react.context_provider'
            - '@logger'
        calls:
            - [setPackage, ['@assets.packages', 'main.js']]
    limenius_react.react_renderer:
        class: App\ReactRenderer\Renderer\PhpExecJsReactRenderer
        arguments:
            - '%kernel.project_dir%/web'
            - '%limenius_react.fail_loud%'
            - '@limenius_react.context_provider'
            - '@logger'
        calls:
            - [setPackage, ['@assets.packages', 'main.js']]
```
